name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: mynance

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Install dependecies
        run: yarn

      - name: Install playwright driver
        run: yarn playwright install chromium

      - name: Create db
        env:
          SERVER_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mynance
        run: yarn db-push

      - name: Run CI
        env:
          SERVER_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mynance
        run: yarn ci
